/**
 *
 * Created by Devin on 2020/12/25.
 * Copyright Devin. All rights reserved.
 *
 */

export default {
    THEME_CHANGE: 'THEME_CHANGE',
    THEME_INIT: 'THEME_INIT',
    SHOW_THEME_VIEW: 'SHOW_THEME_VIEW',
    LOAD_USER_INFO: 'LOAD_USER_INFO',
    SUBMIT_FEED_BACK: 'SUBMIT_FEED_BACK',
    // index
    REFRESH_INDEX: 'REFRESH_INDEX',
    REFRESH_INDEX_SUCCESS: 'REFRESH_INDEX_SUCCESS',
    REFRESH_INDEX_FAILED: 'REFRESH_INDEX_FAILED',
    // load more
    LOAD_MORE_INDEX_SUCCESS: 'LOAD_MORE_INDEX_SUCCESS',
    LOAD_MORE_INDEX_FAILED: 'LOAD_MORE_INDEX_FAILED',

    RESET_ERROR_MESSAGE :'RESET_ERROR_MESSAGE',
    STARRED_REQUEST :'STARRED_REQUEST',
    STARRED_SUCCESS :'STARRED_SUCCESS',
    STARRED_FAILURE : 'STARRED_FAILURE',
}


